# Generated by Django 5.0.1 on 2024-01-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicname', models.CharField(max_length=255)),
                ('mothername', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('addr', models.TextField()),
                ('statename', models.CharField(max_length=255)),
                ('cityname', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('pno', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
