# Generated by Django 5.0.1 on 2024-01-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('identity_mark', models.CharField(max_length=3)),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('number', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='missing_person_images/')),
            ],
        ),
    ]
