# Generated by Django 5.0.1 on 2024-01-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_missingcase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missingcase',
            old_name='identity_mark',
            new_name='identificationMark',
        ),
        migrations.RenameField(
            model_name='missingcase',
            old_name='full_name',
            new_name='name',
        ),
    ]
