# Generated by Django 5.0.1 on 2024-01-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_identity_mark_missingcase_identificationmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingcase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media-case/'),
        ),
    ]
