# Generated by Django 5.0.1 on 2024-01-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_missingcase_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField()),
                ('crime_no', models.PositiveIntegerField()),
                ('crime_type', models.TextField(max_length=20)),
                ('crime_name', models.TextField(max_length=35)),
                ('age', models.PositiveIntegerField()),
                ('nickname', models.TextField(max_length=15)),
                ('adate', models.DateField()),
                ('dateoc', models.DateField()),
                ('gender', models.TextField()),
                ('address', models.CharField(max_length=60)),
                ('birthmark', models.TextField(max_length=5)),
                ('wanted', models.BooleanField(default=False)),
                ('pending', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='missingcase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
