# Generated by Django 5.0.1 on 2024-01-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_crimereport_alter_missingcase_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crimereport',
            old_name='name',
            new_name='case_id',
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='wanted',
            field=models.TextField(),
        ),
    ]
