# Generated by Django 5.0.1 on 2024-04-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_name_crimereport_case_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralPublic',
        ),
    ]
