# Generated by Django 5.0.1 on 2024-04-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserA',
        ),
    ]
